<a href="https://colab.research.google.com/github/anumit-web/TensorFlow_tutorial_3/blob/main/TensorFlow_test_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow Tutorial

https://www.tensorflow.org/tutorials

In [43]:
print('Hello World')

Hello World


In [44]:
print('TensorFlow tutorial')

TensorFlow tutorial


In [45]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [46]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [47]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [48]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.13118768, -0.15539402,  0.7180616 , -1.0026408 ,  0.4969408 ,
        -0.36937526, -0.08596566, -0.04330623, -0.22306941,  0.31083637]],
      dtype=float32)

In [49]:
tf.nn.softmax(predictions).numpy()

array([[0.08332876, 0.08133589, 0.19481356, 0.03486002, 0.15616642,
        0.06566763, 0.08718356, 0.09098323, 0.07601357, 0.12964731]],
      dtype=float32)

In [50]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [51]:
loss_fn(y_train[:1], predictions).numpy()

2.7231493

In [52]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [53]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2914 - accuracy: 0.9152
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1418 - accuracy: 0.9586
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1034 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0859 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0746 - accuracy: 0.9765


In [54]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0691 - accuracy: 0.9772 - 606ms/epoch - 2ms/step


[0.06907123327255249, 0.9771999716758728]

In [55]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [56]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.7545238e-08, 2.3704212e-07, 1.7860402e-05, 7.3821231e-04,
        7.0212458e-10, 6.1142396e-07, 1.5091205e-12, 9.9913424e-01,
        8.4239218e-06, 1.0046262e-04],
       [6.7997824e-10, 4.7504946e-05, 9.9993789e-01, 1.4400800e-05,
        5.9848437e-13, 8.9843212e-08, 3.8741206e-09, 4.3562096e-15,
        1.1465047e-07, 1.5973180e-14],
       [8.1155470e-08, 9.9953222e-01, 6.7617926e-05, 1.2719768e-06,
        5.7059700e-05, 2.1202939e-06, 5.8269588e-06, 3.1014139e-04,
        2.3527635e-05, 8.4808029e-08],
       [9.9991393e-01, 1.2429266e-10, 4.6496207e-06, 2.7622933e-08,
        2.7613601e-07, 1.6100352e-06, 7.5479686e-05, 3.6713992e-08,
        1.5775441e-08, 4.0003379e-06],
       [2.7147331e-07, 3.8696953e-08, 9.0721087e-06, 2.1780856e-07,
        9.9707830e-01, 2.5242020e-06, 4.2561983e-06, 3.6100620e-05,
        5.9352110e-06, 2.8633117e-03]], dtype=float32)>